### ISSUE TITLE
IndexError on document 2689445_9 from ANTIQUE

### ISSUE THREAD

**Issue by TheMrSheldon** [ielab/CharacterBERT-DR#4]
I would like to use CharacterBERT-DR-ST as an embedding model for ranking with cosine similarity. It usually runs well but reliably fails when I encode document `2689445_9` from ANTIQUE's document collection.

The following is my model definition:
```py
from torch import Tensor

class CharacterBERT():
    def __init__(self) -> None:
        from transformers import BertTokenizer
        from tevatron.modeling import CharacterBertModel, CharacterIndexer
        self.tokenizer = BertTokenizer.from_pretrained("ielabgroup/CharacterBERT-DR-ST")
        self.model = CharacterBertModel.from_pretrained("ielabgroup/CharacterBERT-DR-ST")
        self.indexer = CharacterIndexer()
    
    def _character_bert_tokenize(self, text):
        x = self.tokenizer.basic_tokenizer.tokenize(text)
        x = ['[CLS]', *x, '[SEP]']
        return x

    def __call__(self, input_texts: list[str]) -> Tensor:
        tokens = [self._character_bert_tokenize(t) for t in input_texts]
        batch_ids = self.indexer.as_padded_tensor(tokens)
        output, _ = self.model(batch_ids.to(self.model.device))
        return output[:, 0]
```

I then call the model via
```py
model = CharacterBERT()
# document 2689445_9 from ANTIQUE
doc = "Your life is  for limited years on this earth.  Think....where  you  came from (while took Birth)...,  and  Where  would you  go to  after death.   Remember , this universe  existed for  somany years.....when you  were  not  there...then also this earth was there....when you would have gone out of this world, then also, the  earth would  remain.     Hence, you  are  a  guest  for few  years on this earth.    Please  be  creative,  enjoy every moments, gain knowledge, help others, educate your children , love your family,  society.....  Ensure,  nothing. wrong happens to this  beautiful universe of God.  Donot support mass destruction...     Your  life  is  precious,  ...imagine...how  blood  runs in your  vain...how  you take  free  oxygen given by god...to make your  life  leaving,  how  you walk  on this  earth...whereas, difficult to walk on Moon  etc...    . . Think, you are  eating/drinking  holding your head high,  whereas  animals  eat /drink bowing their hand down... Also, remember, ....you can eat/drink and swallow ,,,,,only if  the  Gravitational force on earth keep working......   otherwise  difficult to  eat  /drink  at  Moon,,,,,where  there is  no  gravitational force...... . You  are  lucky  to have got  human life...with  creative brains.....use them  for  betterment of the society/ your own family.......etc.....you can  enjoy life.......and appreciate  this  life.....and  creator  of life on the earth.....!!!. . . You  may be from any religion.......but  truth is  that you  are  the  beautiful  creation of  God  which  is  only  ONE...............and prevails  everywhere........and HE  doesnot  discriminate between human beings.......  All humans  being  express happyness  in similar fashion by  . smiling/showing teeth  etc....    It  never happens that  a    Muslim  laughs  from mouth,  and Christian laughs  from stomach  or  Hindu  laughs  from  head.....etc...... . But,  every person on this earth  are different  than others...even  brothers  in same  family from  same parents  are  different  and borne with unique  personality..... This  is  the rule of  God....... . Imagine,,,if all humans are borne  alike......... Imagine.....if  humans  start  eating from  leg..... Imagine....humans ..........start walking  underground...... . . ??????"
model([doc])
```

This always fails with the following error:
```
Traceback (most recent call last):
  File "/workspaces/myproject/tmp/repro.py", line 24, in <module>
    model([doc])
  File "/workspaces/myproject/tmp/repro.py", line 18, in __call__
    output, _ = self.model(batch_ids.to(self.model.device))
  File "/home/dev/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/tevatron/modeling.py", line 1001, in forward
    embedding_output = self.embeddings(
  File "/home/dev/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/tevatron/modeling.py", line 863, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dev/.local/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home/dev/.local/lib/python3.10/site-packages/torch/nn/functional.py", line 2233, in embedding
    return torch.embedding(weight, input,
```

Is my model definition correct or is this a bug?

Thank you very much for your help.

**Comment by ArvinZhuang** [comment]
Hi, could you please share the full error trace? 
but seems the error is coming from position_embeddings and the doc is pretty long. I guess that might be due to the input text exceeding the token length limitation?
If this is the case you probably need to truncate your doc. 
I think you can achieve this by setting `batch_ids = self.indexer.as_padded_tensor(tokens, maxlen=512)`

**Comment by TheMrSheldon** [comment]
Thank you very much for the fast response.

That did the trick.
